#!/usr/bin/env python3
"""
Configure Gemini API key to .env file for VisionCraft Pro
"""

import os
import sys
from pathlib import Path

def configure_gemini_env():
    """Configure Gemini API key in .env file"""
    print("🤖 Configuring Gemini API key for VisionCraft Pro")
    print("=" * 55)
    print()

    # Gemini API key from previous context
    gemini_key = "AIzaSyCsGf1WwZu20G9pHcf1mWFaCP1SCnAgjec"

    print(f"🔑 Using Gemini API key: {gemini_key[:20]}...")
    print()

    # Check current directory
    env_file = Path(".env")

    # Read existing .env file if it exists
    existing_env = {}
    if env_file.exists():
        print("📄 Reading existing .env file...")
        try:
            with open(env_file, 'r', encoding='utf-8') as f:
                for line in f:
                    line = line.strip()
                    if line and not line.startswith('#'):
                        if '=' in line:
                            key, value = line.split('=', 1)
                            existing_env[key.strip()] = value.strip()
            print(f"✅ Found {len(existing_env)} existing environment variables")
        except Exception as e:
            print(f"⚠️  Could not read existing .env file: {e}")
    else:
        print("📄 Creating new .env file...")

    print()

    # Update or add Gemini API key
    existing_env["GEMINI_API_KEY"] = gemini_key

    # Write back to .env file
    try:
        with open(env_file, 'w', encoding='utf-8') as f:
            f.write("# VisionCraft Pro Environment Variables\n")
            f.write("# Generated by configure_gemini_env.py\n")
            f.write("\n")
            for key, value in sorted(existing_env.items()):
                f.write(f"{key}={value}\n")

        print("✅ Successfully updated .env file")
        print(f"📍 Location: {env_file.absolute()}")

    except Exception as e:
        print(f"❌ Failed to write .env file: {e}")
        return False

    print()

    # Set environment variable for current session
    os.environ["GEMINI_API_KEY"] = gemini_key
    print("✅ Environment variable set for current session")

    print()

    # Test the configuration
    print("🧪 Testing Gemini configuration...")
    try:
        from prompt_enhancer import PromptEnhancer

        enhancer = PromptEnhancer()
        print(f"🤖 AI Available: {enhancer.ai_available}")
        print(f"🔑 Gemini Key Set: {bool(enhancer.gemini_key)}")

        if enhancer.ai_available:
            print("🚀 Testing AI enhancement...")
            result = enhancer.enhance_prompt("a beautiful landscape", "photorealistic", "medium")

            print(f"✅ AI Enhanced: {result.get('ai_enhanced', False)}")
            print(f"📝 Enhanced prompt: {result.get('prompt', 'No prompt')[:100]}...")

            if result.get('ai_enhanced'):
                print("🎉 Gemini AI enhancement is working!")
            else:
                print("⚠️  AI enhancement not used (may be due to missing packages)")
        else:
            print("❌ AI not available - check package installation")

    except Exception as e:
        print(f"❌ Error testing Gemini: {e}")
        print("💡 Make sure AI packages are installed: pip install google-generativeai")

    print()

    # Instructions for permanent setup
    print("📋 Next Steps:")
    print("1. ✅ .env file created/updated with Gemini API key")
    print("2. 🔄 Restart the server: python app.py")
    print("3. 🎨 Try prompt enhancement - should now use Gemini AI!")
    print()
    print("🔍 Check .gitignore to ensure .env is protected:")
    gitignore_path = Path(".gitignore")
    if gitignore_path.exists():
        with open(gitignore_path, 'r') as f:
            if '.env' in f.read():
                print("✅ .env file is gitignored (safe)")
            else:
                print("⚠️  .env file is NOT gitignored - add it to .gitignore!")
    else:
        print("⚠️  No .gitignore file found")

    return True

def check_gitignore():
    """Check if .env is properly gitignored"""
    gitignore_path = Path(".gitignore")

    if not gitignore_path.exists():
        print("⚠️  No .gitignore file found")
        return False

    with open(gitignore_path, 'r') as f:
        content = f.read()

    if '.env' in content:
        print("✅ .env file is properly gitignored")
        return True
    else:
        print("⚠️  .env file is NOT gitignored")
        print("💡 Add '.env' to your .gitignore file to protect API keys")
        return False

if __name__ == "__main__":
    try:
        success = configure_gemini_env()
        print()

        if success:
            print("🎉 Gemini API key configuration complete!")
            check_gitignore()
        else:
            print("❌ Configuration failed")
            sys.exit(1)

    except KeyboardInterrupt:
        print("\n⚠️  Configuration cancelled by user")
        sys.exit(1)
    except Exception as e:
        print(f"❌ Unexpected error: {e}")
        sys.exit(1)
